name: Update development

on:
  push:
    branches: 
    - master
    
jobs:
  merge:
    name: merge master -> development
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
        
      - name: Merge master -> development
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'development'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
